[package]
authors = ["nward"]
edition = "2018"
name = "kraken"
version = "0.1.0"

[dependencies]
typed-builder = "0.7.0"
iso4217 = "0.3.2"
json = "0.12.4"
serde_json = "1.0.59"
chrono = "0.4.19"
http = "0.2.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.117"
